@startuml
class DestroyMiniMapIcon {
    Start() : void
    Update() : void
}
MonoBehaviour <|-- DestroyMiniMapIcon
DestroyMiniMapIcon --> "key" GameObject
DestroyMiniMapIcon --> "keyIcon" GameObject
@enduml
